### ISSUE TITLE
This is no settings option

### ISSUE THREAD

**Issue by hyoban** [kravetsone/vscode-publint#3]
<img width="1030" alt="image" src="https://github.com/kravetsone/vscode-publint/assets/38493346/61b03483-53ca-46f4-b729-44fc2fa8d1a0">

It should be https://code.visualstudio.com/api/references/contribution-points#Configuration-example

**Comment by kravetsone** [comment]
I'm sorry! My first extension for VS Code... The funny thing is that the settings worked, but were not displayed in the settings

**Comment by kravetsone** [comment]
released at 0.0.4

![image](https://github.com/kravetsone/vscode-publint/assets/57632712/f12016da-8224-40a7-b997-d8ce9d033a1e)
